steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/stefano-lab/production-nft-xr-api', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/stefano-lab/production-nft-xr-api']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'production-nft-xr-api', '--image', 'gcr.io/stefano-lab/production-nft-xr-api', '--region', 'europe-west2', '--platform', 'managed', '--timeout', '899']

images:
- gcr.io/stefano-lab/production-nft-xr-api